server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:h2:file:./data/retro_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:init.sql
  ldap:
    embedded:
      port: 8389
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
    urls: ldap://localhost:8389/dc=springframework,dc=org
    username: uid=admin,ou=system,dc=springframework,dc=org
    password: secret
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
