server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:h2:file:./data/retro_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:init.sql  # 添加这一行
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto